plugins:
- rubocop-md
- rubocop-performance
- rubocop-rake
- rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Metrics:
  Enabled: false

Naming/FileName:
  Exclude:
  - lib/rspec-wait.rb
  - "*.md"

RSpec/BeEq:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/IncludeExamples:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  EnforcedStyle: brackets
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
